### ISSUE TITLE
вылет с ошибкой zBinkFix.dll

### ISSUE THREAD

**Issue by salvationFPS** [dosinabox/g2_steam_fix#11]
![image](https://user-images.githubusercontent.com/17096782/95515705-b92f6e00-09c6-11eb-80de-d93a55771bdc.png)

пробовал по твоему совету BorderlessWindow=1, не помогло
Win 10 pro x64 1909 build (18363.1082)
AMD Ryzen 9 3900X
AMD RX 5700XT

**Comment by slvtn** [comment]
ну в принципе по ошибке понятно что проблема с видео роликами.
помог FixBink=0, но роликов теперь соответственно нет :'(

**Comment by dosinabox** [comment]
Можешь ли ты открыть файлы из папки _work\Data\Video?

**Comment by slvtn** [comment]
> Можешь ли ты открыть файлы из папки _work\Data\Video?

да, через VLC открывается

**Comment by dosinabox** [comment]
Исправлено в Union 1.0m
