### ISSUE TITLE
DX11 

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_steam_fix#12]
>> Этот? https://github.com/Kirides/GD3D11

>Pre-release  v17.7-dev12
>![image](https://user-images.githubusercontent.com/49514764/96577706-af6a0c80-12dc-11eb-868f-e3d7c0827d2c.png)
>у меня он работает корректно. ошибок нет. только призраки не работают это из того что в глаза бросаются.

А у меня нет - требует оригинальный Gothic2.exe. И люди жалуются.
Подскажешь, в чем может быть дело?

![image](https://user-images.githubusercontent.com/39790055/96578360-c0ffe400-12dd-11eb-94e2-2c16cef47ded.png)

_Originally posted by @dosinabox in https://github.com/dosinabox/g2_steam_fix/issues/6#issuecomment-712774095_

**Comment by Kor-Angar** [comment]
нет. не подскажу. я же плохо в этих штуках понимаю. Но вот моя папка, попробую свою сохранить и залить мою. если запуститься то станет немного понятнее :-)

https://yadi.sk/d/cxoJk94Berrr5A

**Comment by Kor-Angar** [comment]
ты уже пришла к тому что бы в стим фикс опционально добавить возможность поставить DX11?

**Comment by dosinabox** [comment]
может быть, но для начала хотелось бы заставить его работать на моей текущей сборке

**Comment by dosinabox** [comment]
запустится ли игра, если ты удалишь файл system/Gothic.exe?

**Comment by Kor-Angar** [comment]
так запускается но при запуске какое то сообщение ругательное появляется
![image](https://user-images.githubusercontent.com/49514764/97181379-4424ac80-17ac-11eb-96ed-7888da56811e.png)

**Comment by Kor-Angar** [comment]
так просто запускается без каких либо сообщений
![image](https://user-images.githubusercontent.com/49514764/97181675-9a91eb00-17ac-11eb-9ad2-04494623ebb1.png)

**Comment by dosinabox** [comment]
В общем, это всего лишь предупреждение и на работу рендера не влияет:
![image](https://user-images.githubusercontent.com/39790055/98450979-a1c4db80-2152-11eb-9848-696e9e7aae5a.png)

А чтобы этого предупреждения не было, нужно чтобы в папке system был файл Gothic.exe репорт-версии 2.6 без модификации для расширения памяти. Потом сделаю.

**Comment by Kor-Angar** [comment]
а у меня почему такого предупреждения нет?

**Comment by dosinabox** [comment]
Потому что у тебя файл Gothic.exe есть.

**Comment by Kor-Angar** [comment]
**SystemPack.ini**
FixBink некорректоно работает с DX11
если FixBink=1 то видео отображается как у меня на стримах, в маленьком прямоугольнике.

сейчас проверил, выключил FixBink
```
FixBink=0
; ... исправления для воспроизведения видео на всех ОС, - включено (1) или выключено (0).
```
видео стали воспроизводится на весь экран

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/140613216-af78146c-3a0d-431b-a20d-50c901443323.png)
теперь такое сообщение стало появляеться

**Comment by Kor-Angar** [comment]
ага. понял. стал появляться потому что я удалил файл gothic.exe

**Comment by Kor-Angar** [comment]
как то вообщем оно влияет на производительность. запуск без  файла gothic.exe и с файлом 1:40:00 https://youtu.be/ZTjmxbIexyw?t=6029

**Comment by Kor-Angar** [comment]
он не значительное поднимает фпс. если фпс низкий это заметно. а если высокий не заметно

**Comment by dosinabox** [comment]
Начиная с v17.8-dev2 (SaiyansKing) Gothic2.exe больше не проверяется.

**Comment by Kor-Angar** [comment]
с последним  DX11  всё равно ошибка
![image](https://user-images.githubusercontent.com/49514764/160291563-ced0985e-6977-4cf0-a2b8-7d2fab7050ed.png)

**Comment by dosinabox** [comment]
SaiyansKing или Kirides?

**Comment by Kor-Angar** [comment]
о.. а их две? :-) вот эта
https://vk.com/away.php?to=https%3A%2F%2Fgithub.com%2Fkirides%2FGD3D11%2Freleases%2Fdownload%2Fv17.8-dev4-ci%2FGD3D11-v17.8-dev4-ci.zip&cc_key=

**Comment by dosinabox** [comment]
> о.. а их две? :-) вот эта **Kirides** https://github.com/kirides/GD3D11/releases

Kirides - изначальный автор. SaiyansKing создал свое ответвление от этой работы и делал свои улучшения и исправления. Недавно Kirides взял все эти изменения от SaiyansKing и объединил их со своим проектом. Видимо, объединение не коснулось этой проверки) Можешь пока использовать версию от SaiyansKing и поставить плюсик к моему запросу для Kirides:
https://github.com/kirides/GD3D11/issues/99

**Comment by Kor-Angar** [comment]
> Можешь пока использовать версию от SaiyansKing

у меня такой ошибки нет :-) это сегодня мне в вк писали про эту ошибку :-)

> поставить плюсик к моему запросу для Kirides:

не увидел где плючик ставить :-) или ты имела коммента / лайк ? :-)

**Comment by dosinabox** [comment]
Так хорошо)
![image](https://user-images.githubusercontent.com/39790055/160295812-3ccfcd00-6295-4830-8a35-ae8a058fdebf.png)

**Comment by Kor-Angar** [comment]
ясно :-)
