### ISSUE TITLE
Не работают секретные кнопки в доме Валентино и доме судьи. 

### ISSUE THREAD

**Issue by igorKryvenko** [dosinabox/g2_steam_fix#13]
При прохождении квеста на 6 кровавых кубков, не открываються тайные комнаты в доме судьи и доме Валентино.

**Comment by dosinabox** [comment]
При игре в оригинал или с неофициальным обновлением?

**Comment by dosinabox** [comment]
Главная причина (одинаковые названия стен-муверов) исправлена в 26 версии неофициального обновления.
