### ISSUE TITLE
Gothic2.exe версия 2.7.0.1

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_steam_fix#14]
пакость такая откуда то  взялась. кажется стим закачал.

[Gothic2.zip](https://github.com/dosinabox/g2_steam_fix/files/5519427/Gothic2.zip)

**Comment by dosinabox** [comment]
> кажется стим закачал.

именно так

**Comment by Kor-Angar** [comment]
а в связи с чем они его обновили?

**Comment by dosinabox** [comment]
Не обновляли с 2016 года:
![image](https://user-images.githubusercontent.com/39790055/102908447-899de700-4488-11eb-886e-a673e02c714e.png)

Иногда стим может обнаружить нарушение целостности контента игры и перекачать измененные файлы. Очень редко, но такое случается.
