### ISSUE TITLE
System Pack

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_steam_fix#2]
Скинь пожалуйста сюда патч на доспехи для System Pack

**Comment by Kor-Angar** [comment]
можно что то сделать что бы файл ini в сборке был с комментариями?
[SP-desc (3).txt](https://github.com/dosinabox/g2_steam_fix/files/4874781/SP-desc.3.txt)

**Comment by dosinabox** [comment]
Что-то ты не с той стороны зашел. У меня и патч на доспехи был, и конфиг с комментариями. Моя сборка по какой-то причине у тебя не установилась или установилась не туда. Сначала нужно было выяснить эту причину. А вместо этого ты опять собираешь игру по кусочкам)
[SystemPack.zip](https://github.com/dosinabox/g2_steam_fix/files/4875194/SystemPack.zip)

**Comment by Kor-Angar** [comment]
Вот оно.. появилось :-)

**Comment by Kor-Angar** [comment]
а скинь пожалуйста SystemPack.ini из твой сборки. он же у тебя на русском?

**Comment by dosinabox** [comment]
https://github.com/dosinabox/g2_steam_fix/blob/master/SystemPack.ini

**Comment by Kor-Angar** [comment]
а такая табличка в связи с чем возникает?
![image](https://user-images.githubusercontent.com/49514764/140609665-58fc57f9-732c-4000-9b79-82f31bc59eb6.png)

**Comment by dosinabox** [comment]
При запуске? Это создание виртуальной файловой системы. При установленном SP/Union этого нет, там всё свое, современное и быстрое.

**Comment by Kor-Angar** [comment]
то есть при запуске это происходит значит SP/Union отвалился?

**Comment by Kor-Angar** [comment]
переуставил юнион, добавил твой системпак.ини и всё стало ок. а быстрый сейв из системпак.ини убрали?

**Comment by dosinabox** [comment]
> то есть если при запуске это происходит значит SP/Union отвалился?

да

> а быстрый сейв из системпак.ини убрали?

Не знаю, вроде в Г2 это работало и так? useQuickSaveKeys=1 в Gothic.ini и F5/F9.

**Comment by Kor-Angar** [comment]
просто смотрю что в старом  SystemPack.ini он был, а у тебя нет. вот решил переуточнить :-)

> QuickSaveEnable=1
> ; ... исправление, восстанавливает работоспособность функции быстрого сохранения/загрузки для игры "Готика 1", - включено (1)
> ; или выключено (0), по-умолчанию: 1. Функция быстрого сохранения в игре использует 15-й слот.
> ; клавиши управления: [F5] - быстрое сохранение, [F9] - быстрая загрузка.
> 
> USInternationalKeyboardLayout=1
> ; ... частично меняет раскладку клавиатуры, клавиши Z и Y поменялись местами, клавиша минус (нижнее подчеркивание)
> ; теперь работает корректно в консоли, по-умолчанию: 1.
> 
> Polish_version=0
> ; ... включает изменения сделанные польским локализатором для клавиатуры в игре, - включено (1) или выключено (0), по-умолчанию: 0.

**Comment by dosinabox** [comment]
QuickSaveEnable это для Г1. Я стараюсь разграничивать ini для Г1 и Г2, чтобы в каждом были только настройки под нужную игру и общие. Но когда-нибудь плюну и буду поддерживать только один, в котором будут все настройки в одной куче)

**Comment by Kor-Angar** [comment]
> QuickSaveEnable это для Г1. Я стараюсь разграничивать ini для Г1 и Г2, чтобы в каждом были только настройки под нужную игру и общие. Но когда-нибудь плюну и буду поддерживать только один, в котором будут все настройки в одной куче)

понятно. это многое объясняет :-) это хорошо что находишь возможность поддерживать разные  ini для Г1 и Г2. но плохо что в самом ini  нет  разбивки настроек для разных движков.

**Comment by Kor-Angar** [comment]
Извини пожалуйста. Как то много всего стало происходит после обновления Юниона :-) у героя руны перевернулись, как их можно вернуть в классическое положение?
![20211106202810_1](https://user-images.githubusercontent.com/49514764/140618543-144dbdb3-0a01-4dbc-92dd-b1888ac41349.jpg)

**Comment by dosinabox** [comment]
У меня всё хорошо:
![20211106205718_1](https://user-images.githubusercontent.com/39790055/140619348-b1e46b42-4cda-4c88-87ec-44abffd1ce8d.jpg)

**Comment by Kor-Angar** [comment]
твоя сборка. новая игра
![20211106212655_1](https://user-images.githubusercontent.com/49514764/140620088-c61a5224-fe21-4d9c-9dd6-2316cfae8378.jpg)
