### ISSUE TITLE
Gothic not properly shutdown when using Steam Link App

### ISSUE THREAD

**Issue by dibade89** [dosinabox/g2_steam_fix#26]
Hello, if i start Gothic 2 with this patch over Big Picture Mode / Steam Link App and close it via the main menu and try to start it again, Steam prevents the restart, because 'it is already running'. Both the game and the Modstarter are closed and can not be found with the task manager. A restart of the system is necessary to make it run again.
 
The game starts and ends properly, when disabling the steam overlay in the game config.

**Comment by dosinabox** [comment]
Does this happen without patch, on clean version?

**Comment by dibade89** [comment]
In installed Gothic over Steam. Without this patch it would not even start. I installed the patch and nothing else so far.

**Comment by dibade89** [comment]
On normal version gothic would not even start. I installed the patch to get it to work initiallyAm 13.06.2022 14:11 schrieb dosinabox ***@***.***>:
Does this happen without patch, on clean version?
