### ISSUE TITLE
"Крики" героя при получении урона

### ISSUE THREAD

**Issue by SilvesTheRog** [dosinabox/g2_steam_fix#28]
Привет!
А можно попросить засунуть в стим фикс файлы русской озвучки криков героя, когда он получает урон? Установил стимовскую версию, поставил ру озвучку, накатил стим фикс последней версии и заметил, что когда герой получает урон, то эти охи-ахи звучат голосом оригинала, а не Гланца.

Попробовал накатить архивную версию, где ещё есть озвучка + её исправления — там всё норм, Гланц "кричит".

**Comment by dosinabox** [comment]
Эти восстановленные крики мало кому нравились, было решено их больше не использовать. Я тоже считаю их не очень удачными и больше напоминающими тошноту. 
Завтра выложу файл-патч, который снова сделает озвучку от Гланца.

**Comment by dosinabox** [comment]
Скопировать файл из архива в system/autorun:
[SVM_15.zip](https://github.com/dosinabox/g2_steam_fix/files/13690795/SVM_15.zip)
