### ISSUE TITLE
Gothic 2 Steam Fix (International)

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_steam_fix#5]
Gothic 2 Steam Fix (International)  - Steam Overlay and Mod Starter for Gothic 2
https://steamcommunity.com/sharedfiles/filedetails/?id=2240305342

***
А у тебя в стим версии скриншоты делаются через стим?

**Comment by dosinabox** [comment]
Делаются, через оверлей Стима. Работать он начал только с сентябрьской сборки. Его чинили в Union.

**Comment by Kor-Angar** [comment]
этот?
[Uploading Union.zip…]()

**Comment by Kor-Angar** [comment]
заработали :-)
https://steamcommunity.com/sharedfiles/filedetails/?id=2237519930

**Comment by Kor-Angar** [comment]
Давай так же отдельно выложим патч / фикс который разблокирует оверлей и скриншоты. для интуристов. а то там топики много про пляски с бубнами.

**Comment by dosinabox** [comment]
> Давай так же отдельно выложим патч / фикс который разблокирует оверлей и скриншоты. для интуристов. а то там топики много про пляски с бубнами.

Это ты про что? Для иностранцев international версия уже обновлена.

**Comment by Kor-Angar** [comment]
> Это ты про что? Для иностранцев international версия уже обновлена.

не заметил её. а в поиске яндекса и гугла направлять на топики и "инструкции" про то как сделать скриншот и залить их в стим.

**Comment by dosinabox** [comment]
А зачем тогда это новое руководство? Оно дублирует мое и находится в той же языковой категории.

**Comment by Kor-Angar** [comment]
твоё руководство на русском его скорее всего не будет в поисковой выдаче на англ. превью у него тоже на русском, поэтому для  обычных пользователей не очевидно что оно им подходит. 

продублированное всё на англ, имеет заголовок который корректно проиндексируется. превью так же будет понятно для интуристов.

**Comment by dosinabox** [comment]
> твоё руководство на русском его скорее всего не будет в поисковой выдаче на англ

Языков у меня даже больше)
![image](https://user-images.githubusercontent.com/39790055/94352616-ea777800-006f-11eb-8fcc-13d212f2c593.png)

Ставь ссылку на гитхаб, пожалуйста. Так все пользователи будут качать из одного и того же источника. При необходимости я его просто перезаливаю здесь и ссылка остается старой.
`https://github.com/dosinabox/g2_steam_fix/releases/download/09.20/Gothic_2_Steam_Fix_09.2020.exe`

**Comment by Kor-Angar** [comment]
там стоит ссылка на гитхаб. как пройдёт модерацию будет отображаться. языков у тебя больше потому что сделано было до того как стим отменил мультиязычность из-за спама и жалоб пользователей ;-)27.09.2020, 03:19, "dosinabox" <notifications@github.com>:

твоё руководство на русском его скорее всего не будет в поисковой выдаче на англ

Языков у меня даже больше)

Ставь ссылку на гитхаб, пожалуйста. Так все пользователи будут качать из одного и того же источника. При необходимости я его просто перезаливаю здесь и ссылка остается старой.
https://github.com/dosinabox/g2_steam_fix/releases/download/09.20/Gothic_2_Steam_Fix_09.2020.exe

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/94352790-20b5f700-0072-11eb-90c7-2269225ca949.png)

**Comment by Kor-Angar** [comment]
я же специально врезку добавил про русский стимфикс+неоф патч + русская озвучка. 
зачем же в ссылку на скачку лепить русскую версию? :-) ты слишком хорошо думаешь о пользователях. будут качать русскую версию потому что она больше не понимая что она русская, а потом будут путаться и ругаться ;-) 
я до сих пор опции установочный в твоей сборке на 672 метров не освоил.

![image](https://user-images.githubusercontent.com/49514764/94673623-add1a800-031f-11eb-9bf2-2c692a1f516a.png)

**Comment by Kor-Angar** [comment]
и зеркало специально сделал. не нравится яндекс.диск залей  куда нибудь в другое место на гугл диск например. что бы было зеркало.

**Comment by Kor-Angar** [comment]
я это сделал в большой степени для поисковой выдачи яндекса и гугла, так как Стим отлично индексируется и залетает в топ поисковой выдачи.

при всём моем безграничном уважение к твоему труду и труду коллег, но порой без бутылки и пляски с бубнами не разобраться, что зачем и почему. я бы даже сказал категорически не понятно. именно с этой целью для тех у кого разум не так силён, но есть как говорится желание поиграть в Готику и было вынесено это версия в стим.фикс в отдельной топик ;-)

**Comment by Kor-Angar** [comment]
стим обновился и потёр файлы Готики своими. Скачал  Gothic 2 Steam Fix (International) установил. стали появляется при запуске такие вот ошибки

![image](https://user-images.githubusercontent.com/49514764/105682207-35f94000-5f03-11eb-8344-1c7abc504272.png)
![image](https://user-images.githubusercontent.com/49514764/105682285-50cbb480-5f03-11eb-84bc-113149aca337.png)

**Comment by dosinabox** [comment]
А игра потом запускается?

**Comment by Kor-Angar** [comment]
Да. Вторая ошибка исчезла после того как рендер переустановил15:49, 25 января 2021 г., dosinabox <notifications@github.com>:
А игра потом запускается?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
zParserExtender  это тот архив что ты мне скидывала что бы сейвы грузились?

**Comment by Kor-Angar** [comment]
теория: скопировался английский ини файл который по настройкам отличается от русского. возможно файл SystemPack

**Comment by dosinabox** [comment]
> теория: скопировался английский ини файл который по настройкам отличается от русского. возможно файл SystemPack

у них должны быть одинаковые настройки и они не должны приводить к вылету с ошибкой



> zParserExtender это тот архив что ты мне скидывала что бы сейвы грузились?

да

**Comment by Kor-Angar** [comment]
Так вылета нет. Перед стартом ошибка. Щелкаю отмена и игра загружается. у них должны быть одинаковые настройки и они не должны приводить к вылету с ошибкой

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
Так раньше проблем то не было.  Вечером с силами собирусь  попробую поставить твой русский стим фикс. 17:43, 25 января 2021 г., dosinabox <notifications@github.com>:
Теория: твой zParserExtender написан под Union 1.0i, а в сборке ещё старый 1.0h.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/113478319-ce2a1d00-9490-11eb-803c-ed7f99f7ae4f.png)
давай прямую ссылку уберем  на русскую версию, что бы кому надо уходил в топик по русскому стим фиксу и  уже оттуда качал свежую версию.

**Comment by dosinabox** [comment]
готово

**Comment by Kor-Angar** [comment]
гуд:-)
