### ISSUE TITLE
ОФФ-ТОП g2_steam_fix

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_steam_fix#6]
а что это за плюсики зеленые у меня появились?
![image](https://user-images.githubusercontent.com/49514764/94133544-766b8300-fe69-11ea-9ce4-5d7ea1d21591.png)

**Comment by dosinabox** [comment]
Это отметка новых предметов. Выключается в настройках игры (Настройки - Плагины).

**Comment by Kor-Angar** [comment]
что то не нашёл. в самой игре?

**Comment by dosinabox** [comment]
да, в игре, из главного меню

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/94144713-2ba63700-fe7a-11ea-9594-1b919dc8d687.png)

**Comment by Kor-Angar** [comment]
наверное я опять неправильно устанавливал через СтимФикс :-)

**Comment by Kor-Angar** [comment]
переустановил. оказывается надо было галку про русскую версию ставить. соответственно если без русской версии устанавливать то в меню про плагины нет.

**Comment by Kor-Angar** [comment]
======================================= UNHANDLED EXCEPTION OCCURED ======================================================
======================================= CRASH INFOS: =====================================================================
Gothic II - 2.6 (fix), Parser Version: 50
User:  USER,  CPUType: 586,  Mem: 0 MB total, 0 MB free
Startup Options:-game:_g2a_nr_scriptpatch_v25.ini
=============================================== CALLSTACK : ==============================================================
0023:004DBAC0 (0x0135FB40 0x0135FC58 0x0082E6F0 0x0082E600) GothicMod.exe, zCMenu::Run()+288 byte(s), P:\dev\g2addon\release\ZenGin\_carsten\zMenu.cpp, line 451i
0023:6C560269 (0x004C7270 0x00402210 0x00401F40 0x00401F50) MSVCR100.dll, malloc()+54 byte(s)

**Comment by dosinabox** [comment]
https://remontka.pro/msvcr100-dll-otsutstvuet/

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/94147095-84c39a00-fe7d-11ea-9205-2e9c6af98062.png)
а тут какой лишний?

**Comment by dosinabox** [comment]
Неофициальное обновление распространяется как отдельным модом, так и в составе стим-фикса. Для стим-фикса я делаю некоторые изменения:
_autoscale.mod для стима лишний
_speech_fix.mod уже включен в озвучку
_widescreen.mod уже включен в русифицированные текстуры
_wasteland.mod в стим-фикс не включен, можешь докинуть его отдельно и он подхватится игрой

Пожалуйста, удали игру через стим, удали её папку, установи чистую игру заново, поставь сверху сентябрьский стим-фикс, дополни классикой, шрифтами и dx11. И больше ничего не трогай)

**Comment by Kor-Angar** [comment]
а файлы игры остаются оригинальными или тоже меняются? 

![image](https://user-images.githubusercontent.com/49514764/94231413-a28c1000-ff0c-11ea-815d-c1a755f85f12.png)

**Comment by Kor-Angar** [comment]
> Пожалуйста, удали игру через стим, удали её папку, установи чистую игру заново, поставь сверху сентябрьский стим-фикс, дополни классикой, шрифтами и dx11. И больше ничего не трогай)

так тогда всё будет хорошо и прекрасно. себе то сделать легко, другим сложно ;-)

**Comment by dosinabox** [comment]
> а файлы игры остаются оригинальными или тоже меняются?

Скрипты стим-версии заменяются на оригинальные скрипты русской версии от Акеллы без каких-либо изменений. Если не выбирать опцию русификации текста, то остаются из стим-версии. Также оригинал не использует контент неофициального обновления и плагины Union. Из измененных файлов для оригинала только несколько русифицированных текстур, широкоформатные загрузочные экраны и фон главного меню из Textures_Russian.vdf.

Что за `G2 NotR Unofficial v`? Это не мое)

**Comment by Kor-Angar** [comment]
> Скрипты стим-версии заменяются на оригинальные скрипты русской версии от Акеллы без каких-либо изменений. Если не выбирать опцию русификации текста, то остаются из стим-версии.

и  это прекрасно :-)

> Что за G2 NotR Unofficial v? Это не мое)

это я подписал для себя. 

![image](https://user-images.githubusercontent.com/49514764/94234402-47f5b280-ff12-11ea-8b52-b57fba625dd1.png)
текст можно будет поменять,  ссылка там битая

**Comment by Kor-Angar** [comment]
кажется в  интернациональной версии в файле GothicGame_original.ini указан не тот файл с описанием. 
сейчас идёт Description=!<symlink>**GothicGame**.rtf , а должно быть Description=!<symlink>**GothicGame_original**.rtf

проверь

**Comment by dosinabox** [comment]
В установщик пакуется GothicGame_original.rtf. При установке он переименовывается в GothicGame.rtf.

**Comment by Kor-Angar** [comment]
подскажи пожалуйста а что за файл такой GothicGame.mod который указан в ini файле?

**Comment by dosinabox** [comment]
Вроде как параметр VDF в ini мода/игры не может быть пустым, поэтому разработчики дописывали туда вот такую несуществующую заглушку.

**Comment by Kor-Angar** [comment]
Но у меня это файл есть в папкестимовской версии. А у тебя в стимовской версии он есть? 12:54, 8 октября 2020 г., dosinabox <notifications@github.com>:
Вроде как параметр VDF в ini мода/игры не может быть пустым, поэтому разработчики дописывали туда вот такую несуществующую заглушку.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
А что внутри, сколько весит?

**Comment by Kor-Angar** [comment]
[Uploading GothicGame.zip…]()

**Comment by dosinabox** [comment]
перепроверь ссылку, не загрузилось

**Comment by Kor-Angar** [comment]
[GothicGame.zip](https://github.com/dosinabox/g2_steam_fix/files/5347123/GothicGame.zip)

**Comment by Kor-Angar** [comment]
может появляется при установке G2NotR MDK ?

**Comment by dosinabox** [comment]
> может появляется при установке G2NotR MDK ?

Именно так. А внутри немецкие скрипты. И поэтому неумелые пользователи потом жалуются, что у них игра стала на немецком.
При установке одного только Player Kit этот файл не устанавливается, а запись в ini остается.

**Comment by Kor-Angar** [comment]
> И поэтому неумелые пользователи потом жалуются, что у них игра стала на немецком.

неумелые пользователя доверяют умелым умелым **М**астерам. а умелые Мастера добавляют такую хрень в свои ini файлы в рамках инсталлеров к СтимФикс,  подключая немецкие скрипты и полякам и русским и тем у кого яндекс.диск не работает.. но не всем конечно, а только неумелым пользователям :-D

**Comment by dosinabox** [comment]
Откуда эти немецкие скрипты у юзера берутся, и почему их просто не удалить за ненадобностью (раз уж взялись) - отдельный вопрос. Установить можно много чего, а потом удивляться.

**Comment by Kor-Angar** [comment]
что бы их удалять нужно знать что они есть. они могут взяться в рамках какой то сборке или после установки какого то мода или просто кто кому то скинул архив и предложил скопировать. вообщем есть пользователи у них есть такая вот история. можно им помочь, а можно их ситуацию усугубить. используя право **М**астера. очевидно же что пользователь дебил. и он скорее всего один. а если даже их много он же всё равно кретин ;-) а если среди этих кретинов, сть нормальный пользователь то он же должен включить мозг. ну и так далее :-) я думаю это всё подробно по телевизору нынче рассказывают.

**Comment by dosinabox** [comment]
Какой версией DX11 ты пользуешься?

**Comment by Kor-Angar** [comment]
У меня последняя стоит. 12:15, 20 октября 2020 г., dosinabox <notifications@github.com>:
Какой версией DX11 ты пользуешься?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Этот? https://github.com/Kirides/GD3D11

**Comment by Kor-Angar** [comment]
Pre-release  v17.7-dev12
![image](https://user-images.githubusercontent.com/49514764/96577706-af6a0c80-12dc-11eb-868f-e3d7c0827d2c.png)

у меня он работает корректно. ошибок нет. только призраки не работают это из того что в глаза бросаются.

**Comment by dosinabox** [comment]
> у меня он работает корректно. ошибок нет.

А у меня нет - требует оригинальный Gothic2.exe. И люди жалуются.
Подскажешь, в чем может быть дело?

![image](https://user-images.githubusercontent.com/39790055/96578360-c0ffe400-12dd-11eb-94e2-2c16cef47ded.png)

**Comment by Kor-Angar** [comment]
нет. не подскажу. я же плохо в этих штуках понимаю. Но вот моя папка, попробую свою сохранить и залить мою. если запуститься то станет немного понятнее :-)

https://yadi.sk/d/cxoJk94Berrr5A

**Comment by Kor-Angar** [comment]
даже так? :-)
![image](https://user-images.githubusercontent.com/49514764/97028257-8e1b5180-1564-11eb-88eb-3f1daa3072f7.png)
