### ISSUE TITLE
Gothic 2 Steam Fix (русификация и сборник патчей)

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_steam_fix#8]
ты не хочешь в своём материале добавить информацию по настройкам в инсталлере? 

https://steamcommunity.com/sharedfiles/filedetails/?id=757500304

и сделать лайтовую версию без озвучки? :-)

**Comment by Kor-Angar** [comment]
что то гражданин не то поставил? 
![image](https://user-images.githubusercontent.com/49514764/95009062-a8c66e80-0627-11eb-90b3-9f97c8c7edc0.png)
https://steamcommunity.com/sharedfiles/filedetails/?id=2245357122

**Comment by dosinabox** [comment]
Пусть перезагрузит компьютер. И пусть проверит свойства игры, в давние времена оверлей отключали принудительно, потому что с ним сразу игра крашилась. И потом забывают, что выключали)

**Comment by dosinabox** [comment]
> ты не хочешь в своём материале добавить информацию по настройкам в инсталлере?

А что там непонятного?) Их осталось всего три.
